spring:
  application:
    name: verification-service
  profiles:
    active: local
  cloud:
    config:
      label: main
  config:
    request-read-timeout: 30
    import:
      - configserver:http://localhost:8080
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'





