spring:
  application:
    name: test-service
  profiles:
    active: default
  config:
    request-read-timeout: 30
    import:
      - configserver:http://localhost:8888
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8080



